---
- hosts: all
  become: true
  vars:
    username:
      - corneta
  tasks:

  - name: Install python3 and pip in Ubuntu and CentOS
    package:
     name:
       - python3
       - python3-pip
     state: latest

  - name: set pip3 as default pip for both Ubuntu and CentOS
    command: "ln -sf /usr/bin/pip3 /usr/bin/pip"
    when: (ansible_facts['distribution'] == "Ubuntu") or
           (ansible_facts['distribution'] == "CentOS")

  - name: set python3 as default python for both Ubuntu and CentOS
    command: "ln -sf /usr/bin/python3 /usr/bin/python"
    when: (ansible_facts['distribution'] == "Ubuntu") or
           (ansible_facts['distribution'] == "CentOS")

  - name: Install java open-jdk in Ubuntu and CentOS
    package:
     name:
       - "{{ java_package }}"
     state: latest
     update_cache: yes

  - name: Creating Banner Motd
    template:
      src: motd.j2
      dest: /etc/motd

  - name: Creating a user
    user:
     name: "username"
